<?php

namespace backend\modules\rbac\models;

use Yii;

/**
 * This is the model class for collection "user".
 *
 * @property \MongoDB\BSON\ObjectID|string $_id
 * @property mixed $username
 * @property mixed $auth_key
 * @property mixed $password_hash
 * @property mixed $password_reset_token
 * @property mixed $email
 * @property mixed $status
 * @property mixed $created_at
 * @property mixed $updated_at
 */
class User extends \common\models\User
{
    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        return [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email',
            'status',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','email'],'unique','on' => 'create'],
            [['username','email','password_hash'],'required'],
            [['username', 'auth_key', 'password_hash', 'password_reset_token', 'email', 'status', 'created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Usuario',
            'auth_key' => 'Clave de Autentificación',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Correo Electrónico',
            'status' => 'Estatus',
            'created_at' => 'Creado',
            'updated_at' => 'Actualizado',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->password_hash = Yii::$app->security->generatePasswordHash($this->password_hash);
            $this->status = self::STATUS_ACTIVE;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
